import { Bot, User } from 'lucide-react';

import { Badge } from '@/shared/ui/badge';

interface TranslationStatusProps {
  isMachineTranslated: boolean | null;
  updatedAt?: null | string;
}

/**
 * TranslationStatus – Renders translation provenance and update info
 *
 * Indicates whether a translation was generated by a machine (LLM) or created manually,
 * displaying a labeled badge with an accompanying icon for each state. If available,
 * also shows the last updated date in a localized US format. If no translation
 * metadata is present (`isMachineTranslated === null`), displays a muted fallback message.
 *
 * Provides accessible ARIA labels for badges to assist screen readers. Used in both
 * per-language and default key views to offer a consistent UI for translation status.
 *
 * @param {Object} props - Translation status props
 * @param {boolean | null} props.isMachineTranslated - Whether translation was machine-generated
 *   (`true` = machine/LLM, `false` = manual, `null` = not translated)
 * @param {string | null | undefined} [props.updatedAt] - ISO string of the last update timestamp, if available
 *
 * @returns {JSX.Element} Badge and optional date, or a fallback message if not translated
 */
export function TranslationStatus({ isMachineTranslated, updatedAt }: TranslationStatusProps) {
  // no metadata available
  if (isMachineTranslated === null) {
    return <span className="text-muted-foreground text-xs italic">No translation</span>;
  }

  const formattedDate = updatedAt
    ? new Date(updatedAt).toLocaleDateString('en-US', {
        day: 'numeric',
        month: 'short',
        year: 'numeric',
      })
    : null;

  return (
    <div className="flex items-center gap-4">
      {isMachineTranslated ? (
        <Badge aria-label="Machine translated" className="flex items-center gap-1" variant="secondary">
          <Bot className="h-3 w-3" />
          Machine
        </Badge>
      ) : (
        <Badge aria-label="Manually translated" className="flex items-center gap-1" variant="default">
          <User className="h-3 w-3" />
          Manual
        </Badge>
      )}
      {formattedDate && <span className="text-muted-foreground text-xs">{formattedDate}</span>}
    </div>
  );
}
