import { z } from 'zod';

import type { TranslationResponse, UpdateTranslationRequest } from '@/shared/types';

import {
  TRANSLATION_VALUE_MAX_LENGTH,
  TRANSLATION_VALUE_MIN_LENGTH,
  TRANSLATIONS_ERROR_MESSAGES,
  TRANSLATIONS_UPDATE_SOURCE_VALUES,
} from '@/shared/constants';

// translation value validation (same as used in keys)
const TRANSLATION_VALUE_SCHEMA = z
  .string()
  .min(TRANSLATION_VALUE_MIN_LENGTH, TRANSLATIONS_ERROR_MESSAGES.VALUE_REQUIRED)
  .max(TRANSLATION_VALUE_MAX_LENGTH, TRANSLATIONS_ERROR_MESSAGES.VALUE_TOO_LONG)
  .refine((value) => !value.includes('\n'), TRANSLATIONS_ERROR_MESSAGES.VALUE_NO_NEWLINES)
  .transform((value) => value.trim());

// locale code validation (bcp-47 format)
const LOCALE_CODE_SCHEMA = z.string().regex(/^[a-z]{2}(-[A-Z]{2})?$/, {
  message: 'Locale must be in BCP-47 format (e.g., "en" or "en-US")',
});

// uuid validation schemas
const PROJECT_ID_SCHEMA = z.string().uuid('Invalid project ID format');
const KEY_ID_SCHEMA = z.string().uuid('Invalid key ID format');
const USER_ID_SCHEMA = z.string().uuid('Invalid user ID format');

// update source validation
const UPDATE_SOURCE_SCHEMA = z.enum(TRANSLATIONS_UPDATE_SOURCE_VALUES, {
  errorMap: () => ({ message: 'Update source must be "user" or "system"' }),
});

/**
 * Zod schema for validating update translation request body fields
 *
 * Validates only the body fields that are sent to the database update operation,
 * excluding URL parameters (project_id, key_id, locale). Used internally by
 * the mutation hook to validate the payload before sending to Supabase.
 *
 * Validates:
 * - is_machine_translated: boolean flag indicating if translation was generated by AI
 * - updated_by_user_id: UUID of the user who made the update (nullable)
 * - updated_source: source of the update ('user' or 'system')
 * - value: translation value string (trimmed, no newlines, length constraints)
 *
 * @see UPDATE_TRANSLATION_REQUEST_SCHEMA for full request validation including URL params
 *
 * @type {z.ZodObject}
 */
export const UPDATE_TRANSLATION_REQUEST_BODY_SCHEMA = z.object({
  is_machine_translated: z.boolean(),
  updated_by_user_id: USER_ID_SCHEMA.nullable(),
  updated_source: UPDATE_SOURCE_SCHEMA,
  value: TRANSLATION_VALUE_SCHEMA,
});

/**
 * Zod schema for validating complete update translation request
 *
 * Validates the full UpdateTranslationRequest including all URL parameters
 * (project_id, key_id, locale) and body fields. Used for runtime validation
 * of the complete mutation payload before processing.
 *
 * Validates:
 * - project_id: UUID of the project
 * - key_id: UUID of the translation key
 * - locale: BCP-47 locale code (e.g., "en" or "en-US")
 * - value: translation value (nullable, validated if provided)
 * - is_machine_translated: boolean flag
 * - updated_by_user_id: UUID of the user (nullable)
 * - updated_source: source of the update ('user' or 'system')
 * - updated_at: optional ISO datetime string for optimistic locking
 *
 * @see UPDATE_TRANSLATION_REQUEST_BODY_SCHEMA for body-only validation
 *
 * @type {z.ZodType<UpdateTranslationRequest>}
 */
export const UPDATE_TRANSLATION_REQUEST_SCHEMA = z.object({
  is_machine_translated: z.boolean(),
  key_id: KEY_ID_SCHEMA,
  locale: LOCALE_CODE_SCHEMA,
  project_id: PROJECT_ID_SCHEMA,
  updated_at: z.string().datetime().optional(),
  updated_by_user_id: USER_ID_SCHEMA.nullable(),
  updated_source: UPDATE_SOURCE_SCHEMA,
  value: TRANSLATION_VALUE_SCHEMA.nullable(),
}) satisfies z.ZodType<UpdateTranslationRequest>;

/**
 * Zod schema for validating translation response from database
 *
 * Validates the TranslationResponse structure returned from Supabase queries.
 * Used for runtime type safety when parsing database responses in API hooks.
 *
 * Validates:
 * - project_id: UUID of the project
 * - key_id: UUID of the translation key
 * - locale: BCP-47 locale code
 * - value: translation value string (nullable)
 * - is_machine_translated: boolean flag
 * - updated_by_user_id: UUID of the user (nullable)
 * - updated_source: source of the update ('user' or 'system')
 * - updated_at: ISO datetime string of last update
 *
 * @type {z.ZodType<TranslationResponse>}
 */
export const TRANSLATION_RESPONSE_SCHEMA = z.object({
  is_machine_translated: z.boolean(),
  key_id: KEY_ID_SCHEMA,
  locale: LOCALE_CODE_SCHEMA,
  project_id: PROJECT_ID_SCHEMA,
  updated_at: z.string(),
  updated_by_user_id: USER_ID_SCHEMA.nullable(),
  updated_source: UPDATE_SOURCE_SCHEMA,
  value: z.string().nullable(),
}) satisfies z.ZodType<TranslationResponse>;
