/**
 * Type Definitions Index
 *
 * Central export point for all type definitions used in the i18n-mate application.
 * Re-exports database types and API DTOs for convenient importing throughout the codebase.
 */

// Re-export all database types
export type { CompositeTypes, Database, Enums, Json, Tables, TablesInsert, TablesUpdate } from './database.types';

export { Constants } from './database.types';

// Re-export all DTO and Command Model types
export type {
  ApiErrorResponse,
  ApiResponse,
  ApiResult,
  BulkUpdateTranslationRequest,
  CancelTranslationJobRequest,
  ConflictErrorResponse,
  CreateKeyRequest,
  CreateKeyResponse,
  CreateKeyRpcArgs,
  CreateProjectLocaleRequest,
  CreateProjectRequest,
  CreateProjectWithDefaultLocaleRequest,
  CreateTelemetryEventRequest,
  CreateTranslationJobRequest,
  CreateTranslationJobResponse,
  EventType,
  ExportedTranslations,
  ExportTranslationsData,
  ItemStatus,
  JobStatus,
  Key,
  KeyCreatedProperties,
  KeyDefaultViewListResponse,
  KeyDefaultViewResponse,
  KeyInsert,
  KeyPerLanguageViewListResponse,
  KeyPerLanguageViewResponse,
  KeyResponse,
  KeyUpdate,
  LanguageAddedProperties,
  ListKeysDefaultViewArgs,
  ListKeysDefaultViewParams,
  ListKeysDefaultViewRpcArgs,
  ListKeysPerLanguageParams,
  ListKeysPerLanguageViewArgs,
  ListKeysPerLanguageViewRpcArgs,
  ListProjectLocalesWithDefaultArgs,
  ListProjectsParams,
  ListProjectsWithCountsArgs,
  ListTranslationJobsParams,
  PaginationMetadata,
  PaginationParams,
  PasswordResetRequest,
  PasswordResetResponse,
  Project,
  ProjectCreatedProperties,
  ProjectInsert,
  ProjectListResponse,
  ProjectLocale,
  ProjectLocaleInsert,
  ProjectLocaleResponse,
  ProjectLocaleUpdate,
  ProjectLocaleWithDefault,
  ProjectResponse,
  ProjectUpdate,
  ProjectWithCounts,
  ResendVerificationRequest,
  ResendVerificationResponse,
  ResetPasswordRequest,
  ResetPasswordResponse,
  SignInRequest,
  SignInResponse,
  SignUpRequest,
  SignUpResponse,
  TelemetryEvent,
  TelemetryEventInsert,
  TelemetryEventProperties,
  TelemetryEventResponse,
  TelemetryEventUpdate,
  Translation,
  TranslationCompletedProperties,
  TranslationInsert,
  TranslationJob,
  TranslationJobInsert,
  TranslationJobItem,
  TranslationJobItemInsert,
  TranslationJobItemResponse,
  TranslationJobItemUpdate,
  TranslationJobParams,
  TranslationJobResponse,
  TranslationJobUpdate,
  TranslationMode,
  TranslationResponse,
  TranslationUpdate,
  UpdateProjectLocaleRequest,
  UpdateProjectRequest,
  UpdateSourceType,
  UpdateTranslationRequest,
  ValidationErrorResponse,
  VerifyEmailResponse,
} from './types';

// Re-export type guards
export { isActiveJob, isApiErrorResponse, isApiSuccessResponse, isFinishedJob } from './types';
